# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 17:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='geoip_data',
            field=jsonfield.fields.JSONField(editable=False, null=True),
        ),
    ]
